# "org" ensures this Service is used with the correct Serverless Framework Access Key.
# org: konecta1
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
# app: ses-final
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ses-boot-camp

provider:
  stage: dev
  name: aws
  runtime: nodejs20.x
plugins:
  - serverless-iam-roles-per-function
  - serverless-offline
custom:
  baseUrl: /api/${self:service} # prod/prod-ses-boot-camp
  #baseUrl: /prod/${self:provider.stage}-${self:service} # prod/prod-ses-boot-camp
functions:
  sendEmail:
    handler: dist/ses/sendEmail.handler
    name: sendEmail
    description: Send an email using SES
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ses:SendEmail
        Resource: "*"
    events:
      - http:
          path: ${self:custom.baseUrl}/sendEmail
          method: post
    package:
      patterns:
        - dist/ses/sendEmail.js
  sendSmsServerless:
    handler: dist/sns/sendSms.handler
    name: sendSmsServerless
    description: Send an SMS using SNS
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: "*"
    events:
      - http:
          path: ${self:custom.baseUrl}/sendSms
          method: post
    package:
      patterns:
        - dist/sns/sendSms.js
  getAuthUrlGmail:
    handler: dist/gmail/authGmail.handler
    name: getAuthUrlGmail
    description: Get the URL to authenticate with Gmail
    events:
      - http:
          path: ${self:custom.baseUrl}/authGmail
          method: get
    package:
      patterns:
        - dist/gmail/authGmail.js
  getRedirectUrlGmail:
    handler: dist/gmail/authRedirectGmail.handler
    name: getRedirectUrlGmail
    description: Get the URL to authenticate with Gmail
    events:
      - http:
          path: ${self:custom.baseUrl}/authGmail/redirect
          method: get
    package:
      patterns:
        - dist/gmail/authRedirectGmail.js
  sendEmailGmail:
    handler: dist/gmail/sendEmail.handler
    name: sendEmailGmail
    description: Send an email using Gmail
    events:
      - http:
          path: ${self:custom.baseUrl}/sendEmailGmail
          method: post
    package:
      patterns:
        - dist/gmail/sendEmail.js
resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: bucket-correos-sestest
package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!*/**"
    - "!**"